#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  3 19:27:05 2021

@author: 226sauvage
"""

     

def open4(file_name=None):                                                      
    if file_name is None:                                                       
        file_name = "file.txt"                                                  
    with open(file_name) as reader:                                             
        file_content = reader.readlines()                                       
        for line in file_content:                                               
            print(line)         
            
                                                                                    
if __name__ == "__main__":                                                                                          
     open4()   
     
            